server:
  port: 9092
  servlet:
    context-path: /api

spring:
  application:
    name: TravelPlatform
  datasource:
    url: "jdbc:mysql://localhost:3306/itravel"
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true