server:
  port: 9092
  servlet:
    context-path: /api

spring:
  application:
    name: TravelPlatform
  datasource:
    url: "jdbc:mysql://localhost:3306/itravel"
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            scope:
              - email
              - profile

firebase:
  storage:
    bucket-name:

logging:
  level:
    jakarta.mail: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        security: DEBUG

security:
  jwt:
    signerKey: ""
    valid-duration: 600 # 10 minutes (in seconds)
    issuer: Travel-Platform
    audience: Travel-Platform
  refresh-token:
    secret: ""
    refreshable-duration: 604800 # 1 week (in seconds)
  otp:
    otp-duration: 180 # 3 minutes (in seconds)

google-api: http://localhost:9092/api/oauth2/authorization/google